
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action FileAction1;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action QuitAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.Fixed fixedMain;
	private global::Gtk.MenuBar menubarMain;
	private global::Gtk.DrawingArea drawingArea;
	private global::Gtk.Button btnTest;
    
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction1, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Screenary");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixedMain = new global::Gtk.Fixed ();
		this.fixedMain.Name = "fixedMain";
		this.fixedMain.HasWindow = false;
		// Container child fixedMain.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubarMain'><menu name='FileAction1' action='FileAction1'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubarMain = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubarMain")));
		this.menubarMain.Name = "menubarMain";
		this.fixedMain.Add (this.menubarMain);
		// Container child fixedMain.Gtk.Fixed+FixedChild
		this.drawingArea = new global::Gtk.DrawingArea ();
		this.drawingArea.WidthRequest = 640;
		this.drawingArea.HeightRequest = 480;
		this.drawingArea.Name = "drawingArea";
		this.fixedMain.Add (this.drawingArea);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixedMain [this.drawingArea]));
		w3.X = 79;
		w3.Y = 112;
		// Container child fixedMain.Gtk.Fixed+FixedChild
		this.btnTest = new global::Gtk.Button ();
		this.btnTest.CanFocus = true;
		this.btnTest.Name = "btnTest";
		this.btnTest.UseUnderline = true;
		this.btnTest.Label = global::Mono.Unix.Catalog.GetString ("Test");
		this.fixedMain.Add (this.btnTest);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixedMain [this.btnTest]));
		w4.X = 836;
		w4.Y = 556;
		this.Add (this.fixedMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 885;
		this.DefaultHeight = 622;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.btnTest.Clicked += new global::System.EventHandler (this.OnBtnTestClicked);
	}
}
